//! WASM ↔ Bevy event bridge for openSystem.
//!
//! Decouples the GUI renderer from WASM execution by providing a typed
//! event channel between them:
//!
//! ```text
//!   Bevy input (mouse/keyboard)
//!        │
//!        ▼
//!   EventBridge::push_ui_event(UiEvent)
//!        │
//!        ▼
//!   EventBridge::drain_outbound()    ←── WASM runtime polls this
//!        │
//!        ▼
//!   WasmCallback { action, payload }
//!        │   (host calls WASM exported function)
//!        ▼
//!   WASM app logic → produces UidlPatch
//!        │
//!        ▼
//!   EventBridge::push_uidl_patch(UidlPatch)
//!        │
//!        ▼
//!   EventBridge::drain_patches()    ←── Bevy renderer polls this
//!        │
//!        ▼
//!   Re-render / EcsTree diff
//! ```
//!
//! The bridge is intentionally **synchronous and lock-free** in this MVP —
//! both sides run on the same thread (tokio green thread / Bevy main thread).
//! A future multi-threaded version would wrap queues in `Arc<Mutex<>>`.
//!
//! # Round 10 scope
//! - `UiEvent` — pointer + keyboard events produced by Bevy
//! - `WasmCallback` — action + payload routed to the WASM module
//! - `UidlPatch` — minimal delta produced by WASM, consumed by the renderer
//! - `EventBridge` — the channel that connects both sides
//! - Hit-test integration with `EcsTree::hit_test`

use crate::uidl_to_ecs::{EcsTree, EntityId};
use std::collections::VecDeque;

// ─── UI events (Bevy → bridge) ───────────────────────────────────────────────

/// A pointer or keyboard event generated by the Bevy input system.
#[derive(Debug, Clone, PartialEq)]
pub enum UiEvent {
    /// Left-button click at canvas coordinates `(x, y)`.
    Click { x: f32, y: f32 },
    /// Mouse cursor moved to `(x, y)`.
    Hover { x: f32, y: f32 },
    /// Text was typed into an Input widget identified by `entity_id`.
    TextInput { entity_id: EntityId, text: String },
    /// A key was pressed (raw key name, e.g. "Enter", "Escape").
    KeyPress { key: String },
}

// ─── WASM callbacks (bridge → WASM runtime) ──────────────────────────────────

/// A callback that the host should invoke on the WASM module.
///
/// The host calls the WASM export named `action` with `payload` as argument.
/// Convention: `action` is the string from `WidgetComponent::Button::action`
/// or `WidgetComponent::Input::on_change`.
#[derive(Debug, Clone, PartialEq)]
pub struct WasmCallback {
    /// WASM export function name (e.g. `"timer.start"`, `"on_input_change"`).
    pub action: String,
    /// JSON-encoded argument passed to the WASM function.
    pub payload: serde_json::Value,
}

// ─── UIDL patches (WASM → bridge → renderer) ─────────────────────────────────

/// A minimal UI diff produced by a WASM app in response to user events.
///
/// Round 10 MVP supports text/label updates and visibility toggles.
/// Full structural diffs (add/remove nodes) are deferred to v2.1.
#[derive(Debug, Clone, PartialEq)]
pub enum UidlPatch {
    /// Update the text content of a widget by its UIDL string id.
    SetText {
        /// UIDL widget `id` field (set by the app author).
        widget_id: String,
        new_content: String,
    },
    /// Update the label on a button.
    SetButtonLabel {
        widget_id: String,
        new_label: String,
    },
    /// Show or hide a widget.
    SetVisible {
        widget_id: String,
        visible: bool,
    },
    /// Replace the entire document (full re-render).
    FullReplace {
        uidl_json: String,
    },
}

// ─── EventBridge ─────────────────────────────────────────────────────────────

/// Bidirectional event channel between the Bevy renderer and WASM runtime.
///
/// # Lifecycle
///
/// 1. Bevy input handler calls `push_ui_event(event)`
/// 2. The WASM host calls `process_events(tree)` to convert events → callbacks
/// 3. The WASM runtime drains callbacks via `drain_outbound()` and calls WASM
/// 4. WASM app calls `__opensystem_ui_update` → decoded as `UidlPatch`
/// 5. The renderer drains patches via `drain_patches()` and updates the EcsTree
#[derive(Debug, Default)]
pub struct EventBridge {
    /// Pending UI events from Bevy, waiting to be processed.
    inbound: VecDeque<UiEvent>,
    /// Callbacks destined for the WASM runtime.
    outbound: VecDeque<WasmCallback>,
    /// UIDL patches from WASM, waiting for the renderer to apply.
    patches: VecDeque<UidlPatch>,
}

impl EventBridge {
    /// Create a new, empty bridge.
    pub fn new() -> Self {
        Self::default()
    }

    // ── Inbound (Bevy → bridge) ──────────────────────────────────────────────

    /// Enqueue a UI event from the Bevy input system.
    pub fn push_ui_event(&mut self, event: UiEvent) {
        self.inbound.push_back(event);
    }

    /// Convert all pending UI events to WASM callbacks using the current
    /// `EcsTree` for hit-testing and action resolution.
    ///
    /// Should be called once per frame, before draining outbound callbacks.
    pub fn process_events(&mut self, tree: &EcsTree) {
        while let Some(event) = self.inbound.pop_front() {
            match event {
                UiEvent::Click { x, y } => {
                    if let Some(node) = tree.hit_test(x, y) {
                        if let Some(action) = node.action() {
                            self.outbound.push_back(WasmCallback {
                                action: action.to_string(),
                                payload: serde_json::json!({
                                    "event": "click",
                                    "x": x,
                                    "y": y,
                                    "widget_id": node.uidl_id
                                }),
                            });
                        }
                    }
                }
                UiEvent::Hover { x, y } => {
                    // Hover events are informational; mark interaction state.
                    // In a real Bevy integration this would update
                    // `InteractionState::hovered` on the matching node.
                    // For MVP we just discard hover (no WASM callback).
                    let _ = (x, y);
                }
                UiEvent::TextInput { entity_id, text } => {
                    if let Some(node) = tree.get(entity_id) {
                        if let Some(action) = node.action() {
                            self.outbound.push_back(WasmCallback {
                                action: action.to_string(),
                                payload: serde_json::json!({
                                    "event": "text_input",
                                    "value": text,
                                    "widget_id": node.uidl_id
                                }),
                            });
                        }
                    }
                }
                UiEvent::KeyPress { key } => {
                    // Key events are broadcast — WASM may export a
                    // `__opensystem_on_key` handler. For MVP, skip.
                    let _ = key;
                }
            }
        }
    }

    // ── Outbound (bridge → WASM runtime) ─────────────────────────────────────

    /// Drain all pending WASM callbacks.
    ///
    /// The caller (WASM host) should invoke the named WASM export for each.
    pub fn drain_outbound(&mut self) -> Vec<WasmCallback> {
        self.outbound.drain(..).collect()
    }

    /// Returns `true` if there are WASM callbacks waiting to be dispatched.
    pub fn has_outbound(&self) -> bool {
        !self.outbound.is_empty()
    }

    // ── Patches (WASM → bridge → renderer) ───────────────────────────────────

    /// Enqueue a UIDL patch produced by the WASM app.
    ///
    /// Called by the `__opensystem_ui_update` host function stub (v2.1).
    pub fn push_patch(&mut self, patch: UidlPatch) {
        self.patches.push_back(patch);
    }

    /// Drain all pending UIDL patches for the renderer to apply.
    pub fn drain_patches(&mut self) -> Vec<UidlPatch> {
        self.patches.drain(..).collect()
    }

    /// Returns `true` if there are patches waiting to be applied.
    pub fn has_patches(&self) -> bool {
        !self.patches.is_empty()
    }

    // ── Diagnostics ──────────────────────────────────────────────────────────

    /// Total pending event count (inbound + outbound + patches).
    pub fn pending_count(&self) -> usize {
        self.inbound.len() + self.outbound.len() + self.patches.len()
    }

    /// Discard all queued events, callbacks, and patches.
    ///
    /// Used when switching apps or on full re-render.
    pub fn clear(&mut self) {
        self.inbound.clear();
        self.outbound.clear();
        self.patches.clear();
    }
}

// ─── Patch application ────────────────────────────────────────────────────────

/// Apply a slice of `UidlPatch`es to an `EcsTree` in-place.
///
/// Returns the count of nodes that were actually modified.
///
/// `FullReplace` patches are not handled here — the caller must rebuild the
/// entire `EcsTree` from the new UIDL JSON.
pub fn apply_patches(tree: &mut EcsTree, patches: &[UidlPatch]) -> usize {
    let mut changed = 0;
    for patch in patches {
        match patch {
            UidlPatch::SetText { widget_id, new_content } => {
                for node in tree.nodes.iter_mut() {
                    if node.uidl_id.as_deref() == Some(widget_id.as_str()) {
                        if let crate::uidl_to_ecs::WidgetComponent::Text { content, .. } =
                            &mut node.component
                        {
                            if content != new_content {
                                *content = new_content.clone();
                                changed += 1;
                            }
                        }
                    }
                }
            }
            UidlPatch::SetButtonLabel { widget_id, new_label } => {
                for node in tree.nodes.iter_mut() {
                    if node.uidl_id.as_deref() == Some(widget_id.as_str()) {
                        if let crate::uidl_to_ecs::WidgetComponent::Button { label, .. } =
                            &mut node.component
                        {
                            if label != new_label {
                                *label = new_label.clone();
                                changed += 1;
                            }
                        }
                    }
                }
            }
            UidlPatch::SetVisible { .. } => {
                // Visibility toggle requires an `EcsNode::visible` field;
                // deferred to v2.1 when Bevy handles node visibility natively.
                // Count as changed so callers know a re-render is needed.
                changed += 1;
            }
            UidlPatch::FullReplace { .. } => {
                // Signal: caller must rebuild EcsTree from `uidl_json`.
                // Return immediately — further patches are stale.
                return changed + 1;
            }
        }
    }
    changed
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::uidl::UidlDocument;
    use crate::uidl_to_ecs::build_ecs_tree;

    fn parse_tree(json: &str) -> EcsTree {
        let doc = UidlDocument::parse(json).unwrap();
        build_ecs_tree(&doc, 800, 600).unwrap()
    }

    // ── EventBridge basics ───────────────────────────────────────────────────

    #[test]
    fn test_bridge_new_is_empty() {
        let bridge = EventBridge::new();
        assert_eq!(bridge.pending_count(), 0);
        assert!(!bridge.has_outbound());
        assert!(!bridge.has_patches());
    }

    #[test]
    fn test_push_and_drain_patches() {
        let mut bridge = EventBridge::new();
        bridge.push_patch(UidlPatch::SetText {
            widget_id: "title".into(),
            new_content: "Hello".into(),
        });
        assert!(bridge.has_patches());
        let patches = bridge.drain_patches();
        assert_eq!(patches.len(), 1);
        assert!(!bridge.has_patches());
    }

    #[test]
    fn test_clear_empties_all_queues() {
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::Click { x: 0.0, y: 0.0 });
        bridge.outbound.push_back(WasmCallback {
            action: "test".into(),
            payload: serde_json::json!({}),
        });
        bridge.push_patch(UidlPatch::SetVisible {
            widget_id: "x".into(),
            visible: false,
        });
        assert_eq!(bridge.pending_count(), 3);
        bridge.clear();
        assert_eq!(bridge.pending_count(), 0);
    }

    // ── process_events: click routing ────────────────────────────────────────

    #[test]
    fn test_click_on_button_generates_callback() {
        let tree = parse_tree(r#"{
            "layout": {
                "type": "button",
                "label": "Start",
                "action": "timer.start",
                "id": "btn-start"
            }
        }"#);

        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::Click { x: 5.0, y: 5.0 });
        bridge.process_events(&tree);

        let callbacks = bridge.drain_outbound();
        assert_eq!(callbacks.len(), 1);
        assert_eq!(callbacks[0].action, "timer.start");
        assert_eq!(callbacks[0].payload["event"], "click");
        assert_eq!(callbacks[0].payload["widget_id"], "btn-start");
    }

    #[test]
    fn test_click_on_text_no_callback() {
        let tree = parse_tree(r#"{"layout":{"type":"text","content":"hello"}}"#);
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::Click { x: 5.0, y: 5.0 });
        bridge.process_events(&tree);
        assert!(!bridge.has_outbound());
    }

    #[test]
    fn test_click_outside_canvas_no_callback() {
        let tree = parse_tree(r#"{
            "layout": {"type": "button", "label": "X", "action": "act"}
        }"#);
        let mut bridge = EventBridge::new();
        // Far outside the 800x600 canvas.
        bridge.push_ui_event(UiEvent::Click { x: 9000.0, y: 9000.0 });
        bridge.process_events(&tree);
        assert!(!bridge.has_outbound());
    }

    // ── process_events: text input ───────────────────────────────────────────

    #[test]
    fn test_text_input_generates_callback() {
        let tree = parse_tree(r#"{
            "layout": {
                "type": "input",
                "placeholder": "name",
                "on_change": "on_name_change",
                "id": "inp-name"
            }
        }"#);

        let entity_id = tree.root().unwrap().id;
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::TextInput {
            entity_id,
            text: "Alice".into(),
        });
        bridge.process_events(&tree);

        let callbacks = bridge.drain_outbound();
        assert_eq!(callbacks.len(), 1);
        assert_eq!(callbacks[0].action, "on_name_change");
        assert_eq!(callbacks[0].payload["value"], "Alice");
    }

    #[test]
    fn test_text_input_unknown_entity_no_callback() {
        let tree = parse_tree(r#"{"layout":{"type":"text","content":"x"}}"#);
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::TextInput {
            entity_id: EntityId(9999),
            text: "ignored".into(),
        });
        bridge.process_events(&tree);
        assert!(!bridge.has_outbound());
    }

    // ── process_events: hover / key (no callback) ─────────────────────────────

    #[test]
    fn test_hover_produces_no_outbound_callback() {
        let tree = parse_tree(r#"{"layout":{"type":"button","label":"B","action":"b"}}"#);
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::Hover { x: 5.0, y: 5.0 });
        bridge.process_events(&tree);
        assert!(!bridge.has_outbound());
    }

    #[test]
    fn test_key_press_produces_no_outbound_callback() {
        let tree = parse_tree(r#"{"layout":{"type":"text","content":"x"}}"#);
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::KeyPress { key: "Enter".into() });
        bridge.process_events(&tree);
        assert!(!bridge.has_outbound());
    }

    // ── Multiple events in one frame ─────────────────────────────────────────

    #[test]
    fn test_multiple_clicks_generate_multiple_callbacks() {
        let tree = parse_tree(r#"{
            "layout": {"type":"button","label":"B","action":"act","id":"b"}
        }"#);
        let mut bridge = EventBridge::new();
        bridge.push_ui_event(UiEvent::Click { x: 5.0, y: 5.0 });
        bridge.push_ui_event(UiEvent::Click { x: 6.0, y: 6.0 });
        bridge.process_events(&tree);
        let callbacks = bridge.drain_outbound();
        assert_eq!(callbacks.len(), 2);
    }

    // ── apply_patches ─────────────────────────────────────────────────────────

    #[test]
    fn test_set_text_patch_updates_content() {
        let mut tree = parse_tree(r#"{
            "layout": {"type":"text","content":"old","id":"lbl"}
        }"#);
        let patches = vec![UidlPatch::SetText {
            widget_id: "lbl".into(),
            new_content: "new".into(),
        }];
        let changed = apply_patches(&mut tree, &patches);
        assert_eq!(changed, 1);
        let root = tree.root().unwrap();
        if let crate::uidl_to_ecs::WidgetComponent::Text { content, .. } = &root.component {
            assert_eq!(content, "new");
        } else {
            panic!("expected Text component");
        }
    }

    #[test]
    fn test_set_button_label_patch() {
        let mut tree = parse_tree(r#"{
            "layout": {"type":"button","label":"Go","action":"go","id":"btn"}
        }"#);
        let patches = vec![UidlPatch::SetButtonLabel {
            widget_id: "btn".into(),
            new_label: "Stop".into(),
        }];
        let changed = apply_patches(&mut tree, &patches);
        assert_eq!(changed, 1);
        if let crate::uidl_to_ecs::WidgetComponent::Button { label, .. } =
            &tree.root().unwrap().component
        {
            assert_eq!(label, "Stop");
        } else {
            panic!("expected Button component");
        }
    }

    #[test]
    fn test_patch_no_match_returns_zero() {
        let mut tree = parse_tree(r#"{"layout":{"type":"text","content":"x","id":"a"}}"#);
        let patches = vec![UidlPatch::SetText {
            widget_id: "nonexistent".into(),
            new_content: "y".into(),
        }];
        let changed = apply_patches(&mut tree, &patches);
        assert_eq!(changed, 0);
    }

    #[test]
    fn test_full_replace_patch_returns_nonzero() {
        let mut tree = parse_tree(r#"{"layout":{"type":"text","content":"x"}}"#);
        let patches = vec![UidlPatch::FullReplace {
            uidl_json: r#"{"layout":{"type":"text","content":"y"}}"#.into(),
        }];
        let changed = apply_patches(&mut tree, &patches);
        assert!(changed > 0);
    }

    #[test]
    fn test_set_visible_counts_as_changed() {
        let mut tree = parse_tree(r#"{"layout":{"type":"button","label":"B","action":"b","id":"b"}}"#);
        let patches = vec![UidlPatch::SetVisible {
            widget_id: "b".into(),
            visible: false,
        }];
        let changed = apply_patches(&mut tree, &patches);
        assert_eq!(changed, 1);
    }

    #[test]
    fn test_idempotent_set_text_no_double_count() {
        let mut tree = parse_tree(r#"{"layout":{"type":"text","content":"same","id":"t"}}"#);
        let patches = vec![UidlPatch::SetText {
            widget_id: "t".into(),
            new_content: "same".into(),
        }];
        // Same content → no actual change.
        let changed = apply_patches(&mut tree, &patches);
        assert_eq!(changed, 0);
    }

    // ── UidlPatch derives ─────────────────────────────────────────────────────

    #[test]
    fn test_uidl_patch_clone_eq() {
        let p = UidlPatch::SetText {
            widget_id: "a".into(),
            new_content: "b".into(),
        };
        assert_eq!(p.clone(), p);
    }

    #[test]
    fn test_wasm_callback_debug() {
        let cb = WasmCallback {
            action: "foo".into(),
            payload: serde_json::json!({"k": 1}),
        };
        assert!(format!("{:?}", cb).contains("foo"));
    }
}
