#!/usr/bin/env python3
"""
hardware_resolver.py — Resolves hardware manifest to kernel kconfig fragment.

Usage:
    python3 hardware_resolver.py --manifest hardware_manifest.json --db driver_db.json --output kconfig.fragment
"""

import argparse
import json
import sys
from pathlib import Path


def load_json(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def resolve_drivers(manifest: dict, db: dict, arch: str) -> tuple[list[str], list[str]]:
    """Resolve hardware manifest entries to kconfig lines."""
    kconfig_lines = []
    errors = []

    # Always include base config
    base = db.get("base", {}).get("always", {})
    if "kconfig" in base:
        kconfig_lines.extend(base["kconfig"].splitlines())

    # Storage
    for device in manifest.get("storage", []):
        device_type = device.get("type")
        entry = db.get("storage", {}).get(device_type)
        if entry is None:
            errors.append(f"Unknown storage type: {device_type}")
            continue
        if arch not in entry.get("arch", []):
            errors.append(f"Storage '{device_type}' not supported on arch '{arch}'")
            continue
        kconfig_lines.extend(entry["kconfig"].splitlines())

    # Network
    for device in manifest.get("network", []):
        device_type = device.get("type")
        entry = db.get("network", {}).get(device_type)
        if entry is None:
            errors.append(f"Unknown network type: {device_type}")
            continue
        if arch not in entry.get("arch", []):
            errors.append(f"Network '{device_type}' not supported on arch '{arch}'")
            continue
        kconfig_lines.extend(entry["kconfig"].splitlines())

    # Display
    display_type = manifest.get("display")
    if display_type:
        entry = db.get("display", {}).get(display_type)
        if entry is None:
            errors.append(f"Unknown display type: {display_type}")
        elif arch not in entry.get("arch", []):
            # Fallback to simple-framebuffer
            print(f"  Warning: display '{display_type}' not on arch '{arch}', falling back to simple-framebuffer")
            fb_entry = db.get("display", {}).get("simple-framebuffer")
            if fb_entry:
                kconfig_lines.extend(fb_entry["kconfig"].splitlines())
        else:
            kconfig_lines.extend(entry["kconfig"].splitlines())

    # Input
    for device_type in manifest.get("input", []):
        entry = db.get("input", {}).get(device_type)
        if entry is None:
            errors.append(f"Unknown input type: {device_type}")
            continue
        if arch not in entry.get("arch", []):
            errors.append(f"Input '{device_type}' not supported on arch '{arch}'")
            continue
        kconfig_lines.extend(entry["kconfig"].splitlines())

    return kconfig_lines, errors


def deduplicate(lines: list[str]) -> list[str]:
    """Remove duplicate kconfig lines while preserving order."""
    seen = set()
    result = []
    for line in lines:
        line = line.strip()
        if line and line not in seen:
            seen.add(line)
            result.append(line)
    return result


def main():
    parser = argparse.ArgumentParser(description="Resolve hardware manifest to kconfig fragment")
    parser.add_argument("--manifest", required=True, help="Path to hardware_manifest.json")
    parser.add_argument("--db", default=str(Path(__file__).parent / "driver_db.json"),
                        help="Path to driver_db.json")
    parser.add_argument("--output", default="kconfig.fragment", help="Output kconfig fragment path")
    args = parser.parse_args()

    print(f"Loading manifest: {args.manifest}")
    manifest = load_json(args.manifest)

    print(f"Loading driver DB: {args.db}")
    db = load_json(args.db)

    arch = manifest.get("cpu", "unknown")
    board = manifest.get("board", "unknown")

    # Normalize arch from common names
    arch_map = {
        "qemu64": "x86_64",
        "cortex-a76": "aarch64",
        "sifive-u74": "riscv64",
    }
    arch = arch_map.get(arch, arch)

    print(f"Board: {board}, Arch: {arch}")

    kconfig_lines, errors = resolve_drivers(manifest, db, arch)

    if errors:
        print("Warnings/Errors:")
        for e in errors:
            print(f"  - {e}")

    kconfig_lines = deduplicate(kconfig_lines)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as f:
        f.write(f"# AIOS kconfig fragment for board: {board} (arch: {arch})\n")
        f.write("# Generated by hardware_resolver.py — do not edit manually\n\n")
        for line in kconfig_lines:
            f.write(line + "\n")

    print(f"Generated {len(kconfig_lines)} kconfig options -> {output}")
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
